//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod article;
pub mod article_tag;
pub mod category;
pub mod comment;
pub mod series;
pub mod series_article;
pub mod tag;
pub mod user;
