//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::article::Entity as Article;
pub use super::article_tag::Entity as ArticleTag;
pub use super::category::Entity as Category;
pub use super::comment::Entity as Comment;
pub use super::series::Entity as Series;
pub use super::series_article::Entity as SeriesArticle;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
